name: slidy
description: CLI package manager, template for Flutter and Pipeline (scripts). Generate Modules, Pages, Widgets, BLoCs, MobX, Triple and more.
version: 4.0.0+11
homepage: https://github.com/Flutterando/slidy

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  path: ^1.8.2
  dart_console: ^1.0.0
  http: ^0.13.2
  args: ^2.1.0
  ansicolor: ^2.0.1
  recase: ^4.0.0
  file: ^6.1.0
  yaml: ^3.1.0
  collection: ^1.14.11
  meta: ^1.1.8
  source_span: ^1.7.0
  fhir_yaml: ^0.4.0
  rxdart: ^0.26.0
  io: ^1.0.0
  fpdart: ^0.2.0
  pub_api_client: ^2.2.1
  modular_core: ^2.0.3+1


dev_dependencies:
  build_runner: ^2.0.1
  build_version: ^2.0.3
  test: ^1.16.0-nullsafety.17
  mocktail: ^0.1.1
  build_test: ^2.1.0
  cli_pkg: ^2.1.4
  grinder: ^0.9.2

# dependency_overrides:
#   args: '2.0.0-nullsafety.0'

scripts:
  build: mkdir build\windows & dart compile exe bin\slidy.dart -o build\windows\slidy.exe


executables:
  slidy: main
