name: slidy
description: CLI package manager and template for Flutter. This CLI consists of a way to assemble your project structured by modules, pages, repositories, widgets always following the standards of good practices that has been applied by the community flutter in bigger and more structured projects.
version: 0.1.2
author: Flutterando Team <jacobaraujo7@gmail.com>
homepage: https://github.com/Flutterando/slidy

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  pubspec: ^0.1.1
  http: ^0.12.0+2
  path: ^1.6.2
  yaml: ^2.1.16
  args: ^1.5.2


executables:
  slidy: main
