name: slidy
description: CLI package manager and template for Flutter. Generate Modules, Pages, Widgets, BLoCs, MobX, Triple and more.
version: 3.2.2
homepage: https://github.com/Flutterando/slidy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_console: ^1.0.0
  http: ^0.13.2
  args: ^2.1.0
  ansicolor: ^2.0.1
  recase: ^4.0.0
  file: ^6.1.0
  yaml: ^3.1.0
  collection: ^1.14.11
  meta: ^1.1.8
  source_span: ^1.7.0
  dartz: ^0.10.0-nullsafety.1
  fhir_yaml: ^0.4.0
  rxdart: ^0.26.0
  io: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.1
  build_version: ^2.0.3
  test: ^1.16.0-nullsafety.17
  mocktail: ^0.1.1
  build_test: ^2.1.0
  cli_pkg:
    git: https://github.com/leoafarias/dart_cli_pkg
  grinder: ^0.9.0

# dependency_overrides:
#   args: '2.0.0-nullsafety.0'

scripts:
  build: mkdir build\windows & dart compile exe bin\slidy.dart -o build\windows\slidy.exe


executables:
  slidy: main
