name: slidy
description: CLI package manager and template for Flutter. Generate Modules, Pages, Widgets and BLoCs
version: 1.1.0+1
author: Flutterando Team <jacob@gmail.com>
homepage: https://github.com/Flutterando/slidy

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  pubspec: ^0.1.1
  http: ^0.12.0+2
  path: ^1.6.2
  yaml: ^2.1.16
  args: ^1.5.2


executables:
  slidy: main