# This is a basic workflow that is manually triggered

name: Chocolatey Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-windows:
    name: Cholatey Deploy (Windows)
    runs-on: windows-latest
    env:
      CHOCOLATEY_TOKEN: ${{ secrets.CHOCOLATEY_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup Dart
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable

      - name: Install dependencies
        run: dart get

      - name: Run Builder for Version
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Deploy Chocolatey (Windows)
        run: dart run grinder pkg-chocolatey-deploy